services:
  lint:
    image: buildkite/plugin-linter
    command: ["--id", "cultureamp/example-go"]
    volumes:
      - ".:/plugin:ro"

  tests:
    image: buildkite/plugin-tester:v4.2.0
    volumes:
      - ".:/plugin"
